import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/Header";
import { Toaster } from "@/components/ui/sonner"

const myFont = localFont({ src: '../public/DeathNote.ttf' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(myFont.className, "tracking-[3px] bg-[#090109] text-white")} ><Header/>{children}<Toaster /></body>
    </html>
  );
}
